version: '3.7'

services:

  watermark-app:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: watermark-app
    restart: unless-stopped
    ports:
      - "8001"
    volumes:
      - ~/tmp/:/app/app/tmp/

  nginx:
    restart: unless-stopped
    image: nginx:latest
    ports:
      - 80
    volumes:
      - ./app/dist:/var/www/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=pdf.local
      - VIRTUAL_PORT=80
